#ifndef HELP_H
#define HELP_H

static const char* HELP_TEXT = 
"An extremely fast C/C++ package manager.\n"
"\n"
"Usage: box.exe [OPTIONS] <COMMAND>\n"
"\n"
"Commands:\n"
"  run      Build and run the project's executable\n"
"  init     Create a new project\n"
"  add      Add dependencies to the project\n"
"  remove   Remove dependencies from the project\n"
"  version  Read or update the project's version\n"
"  sync     Update the project's environment\n"
"  lock     Update the project's lockfile\n"
"  export   Export the project's lockfile to an alternate format\n"
"  tree     Display the project's dependency tree\n"
"  tool     Run and install commands provided by C packages\n"
"  c        Manage C versions and installations\n"
"  pip      Manage C packages with a pip-compatible interface\n"
"  venv     Create a virtual environment\n"
"  build    Build the project\n"
"  test     Build and run the project's tests\n"
"  clean    Remove the build directory\n"
"  publish  Upload distributions to an index\n"
"  cache    Manage uv's cache\n"
"  self     Manage the uv executable\n"
"  help     Display documentation for a command\n"
"\n"
"Cache options:\n"
"  -n, --no-cache               Avoid reading from or writing to the cache, instead using a temporary directory for the duration of the operation [env: UV_NO_CACHE=]  \n"
"      --cache-dir <CACHE_DIR>  Path to the cache directory [env: UV_CACHE_DIR=]\n"
"\n"
"C options:\n"
"      --managed-c       Require use of uv-managed C versions [env: UV_MANAGED_C=]\n"
"      --no-managed-c    Disable use of uv-managed C versions [env: UV_NO_MANAGED_C=]\n"
"      --no-c-downloads  Disable automatic downloads of C. [env: \"UV_C_DOWNLOADS=never\"]\n"
"\n"
"Global options:\n"
"  -q, --quiet...                                   Use quiet output\n"
"  -v, --verbose...                                 Use verbose output\n"
"      --color <COLOR_CHOICE>                       Control the use of color in output [possible values: auto, always, never]\n"
"      --native-tls                                 Whether to load TLS certificates from the platform's native certificate store [env: UV_NATIVE_TLS=]\n"
"      --offline                                    Disable network access [env: UV_OFFLINE=]\n"
"      --allow-insecure-host <ALLOW_INSECURE_HOST>  Allow insecure connections to a host [env: UV_INSECURE_HOST=]\n"
"      --no-progress                                Hide all progress outputs [env: UV_NO_PROGRESS=]\n"
"      --directory <DIRECTORY>                      Change to the given directory prior to running the command\n"
"      --project <PROJECT>                          Run the command within the given project directory [env: UV_PROJECT=]\n"
"      --config-file <CONFIG_FILE>                  The path to a `uv.toml` file to use for configuration [env: UV_CONFIG_FILE=]\n"
"      --no-config                                  Avoid discovering configuration files (`pyproject.toml`, `uv.toml`) [env: UV_NO_CONFIG=]\n"
"  -h, --help                                       Display the concise help for this command\n"
"  -V, --version                                    Display the uv version\n";

#endif
